-- MySQL Script generated by MySQL Workbench
-- Sun Dec  5 21:57:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema systemOlympia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema systemOlympia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `systemOlympia` DEFAULT CHARACTER SET utf8 ;
USE `systemOlympia` ;

-- -----------------------------------------------------
-- Table `systemOlympia`.`Usuário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`Usuário` (
  `idMatrícula` INT NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `nomeCompleto` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMatrícula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`Academia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`Academia` (
  `idCodigo` INT NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  PRIMARY KEY (`idCodigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`RegistroAtendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`RegistroAtendimento` (
  `idRegistro` INT NOT NULL,
  `idMatrículaUsuário` INT NOT NULL,
  `idCodigoAcademia` INT NOT NULL,
  PRIMARY KEY (`idRegistro`),
  INDEX `fk_Registro_Usuário_idx` (`idMatrículaUsuário` ASC) VISIBLE,
  INDEX `fk_Registro_Academia1_idx` (`idCodigoAcademia` ASC) VISIBLE,
  CONSTRAINT `fk_Registro_Usuário`
    FOREIGN KEY (`idMatrículaUsuário`)
    REFERENCES `systemOlympia`.`Usuário` (`idMatrícula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registro_Academia1`
    FOREIGN KEY (`idCodigoAcademia`)
    REFERENCES `systemOlympia`.`Academia` (`idCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`Plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`Plano` (
  `idPlano` INT NOT NULL,
  `nomePlano` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(10) NOT NULL,
  `benefícios` VARCHAR(45) NOT NULL,
  `idMatrículaUsuário` INT NOT NULL,
  PRIMARY KEY (`idPlano`),
  INDEX `fk_Plano_Usuário1_idx` (`idMatrículaUsuário` ASC) VISIBLE,
  CONSTRAINT `fk_Plano_Usuário1`
    FOREIGN KEY (`idMatrículaUsuário`)
    REFERENCES `systemOlympia`.`Usuário` (`idMatrícula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`Profissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`Profissional` (
  `idMatricula` INT NOT NULL,
  `nomeCompleto` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  `profissao` VARCHAR(20) NOT NULL,
  `numeroRegistro` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `servico` VARCHAR(45) NOT NULL,
  `produtos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMatricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`AgendaProfissional/Academia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`AgendaProfissional/Academia` (
  `idAgendaProfissional/Academia` INT NOT NULL,
  `disponiblidadeProfissional` VARCHAR(45) NULL,
  `idCodigoAcademia` INT NOT NULL,
  `idMatriculaProfissional` INT NOT NULL,
  PRIMARY KEY (`idAgendaProfissional/Academia`),
  INDEX `fk_Agenda_Academia1_idx` (`idCodigoAcademia` ASC) VISIBLE,
  INDEX `fk_Agenda_Profissional1_idx` (`idMatriculaProfissional` ASC) VISIBLE,
  CONSTRAINT `fk_Agenda_Academia1`
    FOREIGN KEY (`idCodigoAcademia`)
    REFERENCES `systemOlympia`.`Academia` (`idCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agenda_Profissional1`
    FOREIGN KEY (`idMatriculaProfissional`)
    REFERENCES `systemOlympia`.`Profissional` (`idMatricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`Servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`Servicos` (
  `idServicos` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idServicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`Plano/Profissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`Plano/Profissional` (
  `idPlano` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `idMatriculaProfissional` INT NOT NULL,
  INDEX `fk_Plano/Profissional_Plano1_idx` (`idPlano` ASC) VISIBLE,
  INDEX `fk_Plano/Profissional_Profissional1_idx` (`idMatriculaProfissional` ASC) VISIBLE,
  CONSTRAINT `fk_Plano/Profissional_Plano1`
    FOREIGN KEY (`idPlano`)
    REFERENCES `systemOlympia`.`Plano` (`idPlano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plano/Profissional_Profissional1`
    FOREIGN KEY (`idMatriculaProfissional`)
    REFERENCES `systemOlympia`.`Profissional` (`idMatricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`Plano/Servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`Plano/Servicos` (
  `idPlano/Servicos` INT NOT NULL,
  `idPlano` INT NOT NULL,
  `idServicos` INT NOT NULL,
  INDEX `fk_Plano/Servicos_Plano1_idx` (`idPlano` ASC) VISIBLE,
  INDEX `fk_Plano/Servicos_Servicos1_idx` (`idServicos` ASC) VISIBLE,
  CONSTRAINT `fk_Plano/Servicos_Plano1`
    FOREIGN KEY (`idPlano`)
    REFERENCES `systemOlympia`.`Plano` (`idPlano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plano/Servicos_Servicos1`
    FOREIGN KEY (`idServicos`)
    REFERENCES `systemOlympia`.`Servicos` (`idServicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`Servico/Profissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`Servico/Profissional` (
  `idServico/Profissional` INT NOT NULL,
  `idMatriculaProfissional` INT NOT NULL,
  `idServicos` INT NOT NULL,
  INDEX `fk_Servico/Profissional_Profissional1_idx` (`idMatriculaProfissional` ASC) VISIBLE,
  INDEX `fk_Servico/Profissional_Servicos1_idx` (`idServicos` ASC) VISIBLE,
  CONSTRAINT `fk_Servico/Profissional_Profissional1`
    FOREIGN KEY (`idMatriculaProfissional`)
    REFERENCES `systemOlympia`.`Profissional` (`idMatricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servico/Profissional_Servicos1`
    FOREIGN KEY (`idServicos`)
    REFERENCES `systemOlympia`.`Servicos` (`idServicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`Nota Fiscal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`Nota Fiscal` (
  `idNota Fiscal` INT NOT NULL,
  `dataPagamento` DATE NOT NULL,
  `vencimento` VARCHAR(45) NOT NULL,
  `idUsuário` INT NOT NULL,
  INDEX `fk_Nota Fiscal_Usuário1_idx` (`idUsuário` ASC) VISIBLE,
  PRIMARY KEY (`idNota Fiscal`),
  CONSTRAINT `fk_Nota Fiscal_Usuário1`
    FOREIGN KEY (`idUsuário`)
    REFERENCES `systemOlympia`.`Usuário` (`idMatrícula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`Tipos Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`Tipos Produto` (
  `idTipos Produto` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `especificacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipos Produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`Produtos` (
  `idProdutos` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `quantidade` INT NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `IdTipos Produto` INT NOT NULL,
  PRIMARY KEY (`idProdutos`),
  INDEX `fk_Produtos_Tipos Produto1_idx` (`IdTipos Produto` ASC) VISIBLE,
  CONSTRAINT `fk_Produtos_Tipos Produto1`
    FOREIGN KEY (`IdTipos Produto`)
    REFERENCES `systemOlympia`.`Tipos Produto` (`idTipos Produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`Itens/Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`Itens/Produto` (
  `idItens` INT NOT NULL,
  `idNota Fiscal` INT NOT NULL,
  `idProdutos` INT NOT NULL,
  PRIMARY KEY (`idItens`),
  INDEX `fk_Itens_Nota Fiscal1_idx` (`idNota Fiscal` ASC) VISIBLE,
  INDEX `fk_Itens_Produtos1_idx` (`idProdutos` ASC) VISIBLE,
  CONSTRAINT `fk_Itens_Nota Fiscal1`
    FOREIGN KEY (`idNota Fiscal`)
    REFERENCES `systemOlympia`.`Nota Fiscal` (`idNota Fiscal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Itens_Produtos1`
    FOREIGN KEY (`idProdutos`)
    REFERENCES `systemOlympia`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`Tipo Planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`Tipo Planos` (
  `idTipo Planos` INT NOT NULL,
  `idNota Fiscal` INT NOT NULL,
  `idPlano` INT NOT NULL,
  PRIMARY KEY (`idTipo Planos`),
  INDEX `fk_Tipo Planos_Nota Fiscal1_idx` (`idNota Fiscal` ASC) VISIBLE,
  INDEX `fk_Tipo Planos_Plano1_idx` (`idPlano` ASC) VISIBLE,
  CONSTRAINT `fk_Tipo Planos_Nota Fiscal1`
    FOREIGN KEY (`idNota Fiscal`)
    REFERENCES `systemOlympia`.`Nota Fiscal` (`idNota Fiscal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tipo Planos_Plano1`
    FOREIGN KEY (`idPlano`)
    REFERENCES `systemOlympia`.`Plano` (`idPlano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`Academia/Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`Academia/Produto` (
  `idAcademia/Produto` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `idCodigoAcademia` INT NOT NULL,
  `IdProdutos` INT NOT NULL,
  PRIMARY KEY (`idAcademia/Produto`),
  INDEX `fk_Academia/Produto_Academia1_idx` (`idCodigoAcademia` ASC) VISIBLE,
  INDEX `fk_Academia/Produto_Produtos1_idx` (`IdProdutos` ASC) VISIBLE,
  CONSTRAINT `fk_Academia/Produto_Academia1`
    FOREIGN KEY (`idCodigoAcademia`)
    REFERENCES `systemOlympia`.`Academia` (`idCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Academia/Produto_Produtos1`
    FOREIGN KEY (`IdProdutos`)
    REFERENCES `systemOlympia`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`Responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`Responsavel` (
  `idResponsavel` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Academia_idCodigo` INT NOT NULL,
  PRIMARY KEY (`idResponsavel`),
  INDEX `fk_Responsavel_Academia1_idx` (`Academia_idCodigo` ASC) VISIBLE,
  CONSTRAINT `fk_Responsavel_Academia1`
    FOREIGN KEY (`Academia_idCodigo`)
    REFERENCES `systemOlympia`.`Academia` (`idCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`Modalidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`Modalidades` (
  `idModalidades` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idModalidades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`Plano/Modalidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`Plano/Modalidades` (
  `idPlano/Modalidades` INT NOT NULL,
  `idPlano` INT NOT NULL,
  `idModalidades` INT NOT NULL,
  PRIMARY KEY (`idPlano/Modalidades`),
  UNIQUE INDEX `idPlano/Modalidades_UNIQUE` (`idPlano/Modalidades` ASC) VISIBLE,
  INDEX `fk_Plano/Modalidades_Plano1_idx` (`idPlano` ASC) VISIBLE,
  INDEX `fk_Plano/Modalidades_Modalidades1_idx` (`idModalidades` ASC) VISIBLE,
  CONSTRAINT `fk_Plano/Modalidades_Plano1`
    FOREIGN KEY (`idPlano`)
    REFERENCES `systemOlympia`.`Plano` (`idPlano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Plano/Modalidades_Modalidades1`
    FOREIGN KEY (`idModalidades`)
    REFERENCES `systemOlympia`.`Modalidades` (`idModalidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`Modalidades/Profissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`Modalidades/Profissional` (
  `idModalidade/Profissional` INT NOT NULL,
  `idModalidades` INT NOT NULL,
  `idMatriculaProfissional` INT NOT NULL,
  PRIMARY KEY (`idModalidade/Profissional`),
  UNIQUE INDEX `idModalidade/Profissional_UNIQUE` (`idModalidade/Profissional` ASC) VISIBLE,
  INDEX `fk_Modalidade/Profissional_Modalidades1_idx` (`idModalidades` ASC) VISIBLE,
  INDEX `fk_Modalidade/Profissional_Profissional1_idx` (`idMatriculaProfissional` ASC) VISIBLE,
  CONSTRAINT `fk_Modalidade/Profissional_Modalidades1`
    FOREIGN KEY (`idModalidades`)
    REFERENCES `systemOlympia`.`Modalidades` (`idModalidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Modalidade/Profissional_Profissional1`
    FOREIGN KEY (`idMatriculaProfissional`)
    REFERENCES `systemOlympia`.`Profissional` (`idMatricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`Modalidades/Academia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`Modalidades/Academia` (
  `idModalidades/Academia` INT NOT NULL,
  `idCodigoAcademia` INT NOT NULL,
  `idModalidades` INT NOT NULL,
  PRIMARY KEY (`idModalidades/Academia`),
  UNIQUE INDEX `idModalidades/Academia_UNIQUE` (`idModalidades/Academia` ASC) VISIBLE,
  INDEX `fk_Modalidades/Academia_Academia1_idx` (`idCodigoAcademia` ASC) VISIBLE,
  INDEX `fk_Modalidades/Academia_Modalidades1_idx` (`idModalidades` ASC) VISIBLE,
  CONSTRAINT `fk_Modalidades/Academia_Academia1`
    FOREIGN KEY (`idCodigoAcademia`)
    REFERENCES `systemOlympia`.`Academia` (`idCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Modalidades/Academia_Modalidades1`
    FOREIGN KEY (`idModalidades`)
    REFERENCES `systemOlympia`.`Modalidades` (`idModalidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`Profissional/Produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`Profissional/Produtos` (
  `idProfissional/Produtos` INT NOT NULL,
  `idMatriculaProfissional_` INT NOT NULL,
  `idProdutos` INT NOT NULL,
  PRIMARY KEY (`idProfissional/Produtos`),
  UNIQUE INDEX `idProfissional/Produtos_UNIQUE` (`idProfissional/Produtos` ASC) VISIBLE,
  INDEX `fk_Profissional/Produtos_Profissional1_idx` (`idMatriculaProfissional_` ASC) VISIBLE,
  INDEX `fk_Profissional/Produtos_Produtos1_idx` (`idProdutos` ASC) VISIBLE,
  CONSTRAINT `fk_Profissional/Produtos_Profissional1`
    FOREIGN KEY (`idMatriculaProfissional_`)
    REFERENCES `systemOlympia`.`Profissional` (`idMatricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profissional/Produtos_Produtos1`
    FOREIGN KEY (`idProdutos`)
    REFERENCES `systemOlympia`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`AgendaProfissional/Usuário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`AgendaProfissional/Usuário` (
  `idAgendaProfissional/Usuário` INT NOT NULL,
  `disponiblidadeProfissional` VARCHAR(45) NOT NULL,
  `idMatrículaUsuário` INT NOT NULL,
  `idMatriculaProfissional` INT NOT NULL,
  PRIMARY KEY (`idAgendaProfissional/Usuário`),
  UNIQUE INDEX `idAgendaProfissional/Usuário_UNIQUE` (`idAgendaProfissional/Usuário` ASC) VISIBLE,
  INDEX `fk_AgendaProfissional/Usuário_Usuário1_idx` (`idMatrículaUsuário` ASC) VISIBLE,
  INDEX `fk_AgendaProfissional/Usuário_Profissional1_idx` (`idMatriculaProfissional` ASC) VISIBLE,
  CONSTRAINT `fk_AgendaProfissional/Usuário_Usuário1`
    FOREIGN KEY (`idMatrículaUsuário`)
    REFERENCES `systemOlympia`.`Usuário` (`idMatrícula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AgendaProfissional/Usuário_Profissional1`
    FOREIGN KEY (`idMatriculaProfissional`)
    REFERENCES `systemOlympia`.`Profissional` (`idMatricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemOlympia`.`Usuario/Poduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemOlympia`.`Usuario/Poduto` (
  `idUsuario/Poduto` INT NOT NULL,
  `idMatrículaUsuário` INT NOT NULL,
  `idProdutos` INT NOT NULL,
  PRIMARY KEY (`idUsuario/Poduto`),
  INDEX `fk_Usuario/Poduto_Usuário1_idx` (`idMatrículaUsuário` ASC) VISIBLE,
  INDEX `fk_Usuario/Poduto_Produtos1_idx` (`idProdutos` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario/Poduto_Usuário1`
    FOREIGN KEY (`idMatrículaUsuário`)
    REFERENCES `systemOlympia`.`Usuário` (`idMatrícula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario/Poduto_Produtos1`
    FOREIGN KEY (`idProdutos`)
    REFERENCES `systemOlympia`.`Produtos` (`idProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
